services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'

  App\tests\Behat\BehatContext:
    public: true
    arguments:
      - "@kernel"