# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    body_converter:
        enabled: true
    routing_loader: false
#        default_format: json
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ json, html ] }
    view:
        view_response_listener:
            enabled: true
            force: true
    param_fetcher_listener: true
