nelmio_api_doc:
    documentation:
        info:
            title: Way B?
            description: What about your backpack ? est une API permettant de connaître le contenu de son backpack et de le voir évoluer au fil du temps.
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

    models: { use_jms: true }